version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers

    steps:
      - run:
          name: Test
          command: |
            echo 'Listening Code'
            echo 'Este es el Primer Pipeline'
